name: subpixal
channels:
    - http://ssb.stsci.edu/astroconda
    - conda-forge
dependencies:
    - python>=3.5
    - numpy
    - numpydoc
    - scipy
    - astropy
    - nose
    - drizzlepac
    - graphviz
    - matplotlib
    - sphinx
    - pip:
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - sphinx_automodapi
